# Generated by Django 4.1.7 on 2023-03-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_transportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='listing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transportation',
            name='listing_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='no_of_boxes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='onwer_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='owner_phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='owner_pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='truck_requirement',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
