# Generated by Django 4.1.7 on 2023-03-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
    ]
