# Generated by Django 4.1.7 on 2023-03-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='aggrement',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
