# Generated by Django 4.1.7 on 2023-03-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='listing_id',
            field=models.IntegerField(null=True),
        ),
    ]
