# Generated by Django 4.1.7 on 2023-03-12 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0004_listing_aggrement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.BigIntegerField(blank=True, max_length=100)),
                ('adhar_card', models.CharField(blank=True, max_length=100)),
                ('pan_card', models.CharField(blank=True, max_length=100)),
                ('family_members', models.CharField(blank=True, max_length=100)),
                ('aggrement', models.FileField(upload_to='aggrement/%Y/%m/%d')),
                ('listing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
