# Generated by Django 4.1.7 on 2023-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookings_listing_id_alter_bookings_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='listing_id',
            field=models.IntegerField(null=True),
        ),
    ]
