# Generated by Django 4.1.7 on 2023-03-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_bookings_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="currency",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="bookings",
            name="status",
            field=models.CharField(
                choices=[("SUCCESS", "SUCCESS"), ("FAILURE", "FAILURE")],
                max_length=100,
                null=True,
            ),
        ),
    ]
