# Generated by Django 4.1.7 on 2023-03-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_bookings_currency_bookings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='phone_number',
            field=models.BigIntegerField(blank=True),
        ),
    ]
